In [22]:
# Importing necessary libraries
import pennylane as qml
import numpy as np
import matplotlib.pyplot as plt
import random

# Define the number of qubits
n_qubits = 3
shots = 100
# Initialize a device
dev = qml.device('default.qubit', wires=n_qubits, shots=shots)

# Define the initial state preparation function
def initial_state():
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    qml.CNOT(wires=[0, 2])

# Define the weak error function
def apply_weak_error():
    qubit_to_flip = random.randint(0, 2)
    epsilon = np.pi / 3
    qml.RX(epsilon, wires=qubit_to_flip)


@qml.qnode(dev)
def circuit():
    initial_state()
    apply_weak_error()
    
    z1z2 = qml.sample(qml.PauliZ(0) @ qml.PauliZ(1))
    
            
    corrected_state = qml.sample(wires=[0, 1, 2])
    
    # Return all measurements in the order they were taken
    return z1z2, Z1Z2, Z1Z3, corrected_state

# Run the circuit
z1z2, Z1Z2, Z1Z3, corrected_state = circuit()

# Print the stabilizer measurements
print('Z1Z2:', Z1Z2)
print('Z1Z3:', Z1Z3)

# Print the corrected state
print('Corrected state:', corrected_state)

Z1Z2: 1.0
Z1Z3: 0.52
Corrected state: [[1 1 1]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 0]
 [1 1 0]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 0]
 [0 0 0]
 [1 1 1]
 [0 0 1]
 [1 1 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 0]
 [1 1 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [1 1 1]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 0]
 [1 1 1]
 [1 1 0]
 [1 1 1]
 [0 0 1]
 [0 0 0]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 0]
 [1 1 1]
 [0 0 0]
 [1 1 0]
 [1 1 1]
 [0 0 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [1 1 1]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [1 1 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 0]
 [0 0 0]]
